#!/bin/bash
sudo yum install python35 python35-devel python35-pip python35-setuptools python35-virtualenv -y
sudo pip-3.5 install --upgrade pip -y
alias pip='/usr/local/bin/pip3.5'
sudo pip3 install virtualenv
cd /home/ec2-user/app
virtualenv environment
source environment/bin/activate
sudo pip3 install -r requirements.txt
